# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bbb8422f885bb4d63eef1d6a813b3de4d346f6487d025736929cdb0398f730759a130d2e58ca3ee96272ef4ba62370025420069fbb0e8e67368f096963a0b74

test:
  secret_key_base: e35c74776deeb7e40324473cfc6ec63925641c6d2dd0516dbe632b16186e09a9ed7746d4a82b9480b5fd44514c748a4061925702e131e65324cc40e66fb6f3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
