# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bbb8422f885bb4d63eef1d6a813b3de4d346f6487d025736929cdb0398f730759a130d2e58ca3ee96272ef4ba62370025420069fbb0e8e67368f096963a0b74
  mailer_domain: wolox.com.ar
  mailer_password: fh258k3B9Pr7otr5uX22zw
  mailer_username: mailer+test@wolox.com.ar
  gmusr: julianisevilla@gmail.com
  gmpass: 7jis293005
  fb_id: 409441745929255
  fb_secret: 9007fcb3d503241e37b78c40ceda43d9
  gg_id: 447691397628-htcn18us06l8vu076fkpunp5mfbk298n.apps.googleusercontent.com
  gg_secret: TUhPbT0VksnpguyXzDCNz5T2





test:
  secret_key_base: e35c74776deeb7e40324473cfc6ec63925641c6d2dd0516dbe632b16186e09a9ed7746d4a82b9480b5fd44514c748a4061925702e131e65324cc40e66fb6f3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
